branch-defaults:
  master:
    environment: sasha-prod
environment-defaults:
  sasha-prod:
    branch: null
    repository: null
global:
  application_name: sasha
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on
    64bit Amazon Linux/2.7.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: personal
  sc: git
  workspace_type: Application
